### PR TITLE
Debian 10.6 AMI + Add AWS Regions

### PR DESCRIPTION
**Pull request by brianlechthaler**
# Changes:
1) 🇿🇦 Add AWS Capetown, South Africa Region (`af-south-1`)
2) 🇮🇹 Add AWS Milan, Italy Region (`eu-south-1`)
3) Bump all AMIs to Debian Buster 10.6

# References:
1) Debian 10 (Buster) Wiki Article on Official EC2 Images: https://wiki.debian.org/Cloud/AmazonEC2Image/Buster?action=recall&rev=16
2) For information on Debian 10.6, see: https://www.debian.org/News/2020/20200926
3) Official AWS Documentation on Regions and Zones can be found here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
@shaderecker Can you have a look, please?

**Comment by shaderecker** [comment]
Looks good to me. Ship it.

**Comment by t3chn0m4g3** [comment]
> Looks good to me. Ship it.

Thank you 😊

**Comment by t3chn0m4g3** [comment]
@brianlechthaler Thank you!

**Pull request merged**
